master:
  extends:
    file: common.yml
    service: locust
  environment:
    LOCUST_MODE: master
  ports:
    - "8089:8089"
    
slave1:
  extends:
    file: slave.yml
    service: slave
  links:
    - master
   
slave2:
  extends:
    file: slave.yml
    service: slave
  links:
    - master